apiVersion: v1
kind: Service
metadata:
  name: dog-api-service
  namespace: default
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dog-api