"""empty message

Revision ID: 677fb748206d
Revises: e1d35b5944e1
Create Date: 2019-02-01 14:27:22.716056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677fb748206d'
down_revision = 'e1d35b5944e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('name_to_compare', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'dogs', ['name_to_compare'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dogs', type_='unique')
    op.drop_column('dogs', 'name_to_compare')
    # ### end Alembic commands ###
