"""empty message

Revision ID: e1d35b5944e1
Revises: c0f38a740dd1
Create Date: 2019-02-01 14:19:36.201644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d35b5944e1'
down_revision = 'c0f38a740dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('breeds', sa.Column('name_to_compare', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'breeds', ['name_to_compare'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breeds', type_='unique')
    op.drop_column('breeds', 'name_to_compare')
    # ### end Alembic commands ###
